version: 0.0

containers:
  main:
    phases:
      pre_build:
        commands:
          - echo 'Inside CodeBuild Source Directory'
      during_build:
        commands:
          - echo 'Compiling the Ruby Code'
          - ruby HelloWorld.rb
      post_build:
        commands:
          - echo "Would deploy here"
    artifacts:
      type: zip
      files:
        - 'target/test-ruby-sample*'